version: '3.8'

services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: celery -A scout_web worker -l info
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
