# Generated by Django 5.0.7 on 2025-08-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rule_ruleset_scan_configuration_exception_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Exception",
            new_name="RuleException",
        ),
    ]
