# Generated by Django 5.0.7 on 2025-08-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="TicketCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.BigIntegerField(unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=64)),
                ("priority", models.CharField(blank=True, max_length=64, null=True)),
                ("requester_id", models.BigIntegerField(blank=True, null=True)),
                ("company_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("ticket_id", models.BigIntegerField(blank=True, null=True)),
                ("event", models.CharField(max_length=128)),
                ("payload_hash", models.CharField(max_length=64)),
                ("raw", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticket_id", "event"],
                        name="freshdesk_i_ticket__bb63c8_idx",
                    ),
                    models.Index(
                        fields=["payload_hash"], name="freshdesk_i_payload_9612da_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                fields=("payload_hash",), name="uniq_fd_payload_hash"
            ),
        ),
    ]
